"""fix association_table_bonus -> association_table_block_bonuses

Revision ID: 0bbb377ba822
Revises: 85c11a4c4f87
Create Date: 2023-12-23 02:17:43.186081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbb377ba822'
down_revision: Union[str, None] = '85c11a4c4f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_bonus', sa.Column('block_bonuses_id', sa.Integer(), nullable=True))
    op.drop_constraint('association_bonus_buttons_id_fkey', 'association_bonus', type_='foreignkey')
    op.create_foreign_key(None, 'association_bonus', 'block_bonuses', ['block_bonuses_id'], ['id'])
    op.drop_column('association_bonus', 'buttons_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_bonus', sa.Column('buttons_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association_bonus', type_='foreignkey')
    op.create_foreign_key('association_bonus_buttons_id_fkey', 'association_bonus', 'buttons', ['buttons_id'], ['id'])
    op.drop_column('association_bonus', 'block_bonuses_id')
    # ### end Alembic commands ###
