"""#4 -> fix

Revision ID: 2cc074adca1c
Revises: 55ad3fa84bb5
Create Date: 2023-12-16 16:56:10.403591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc074adca1c'
down_revision: Union[str, None] = '55ad3fa84bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('block_mains_terms_button_id_fkey', 'block_mains', type_='foreignkey')
    op.drop_column('block_mains', 'terms_button_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_mains', sa.Column('terms_button_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('block_mains_terms_button_id_fkey', 'block_mains', 'buttons', ['terms_button_id'], ['id'])
    # ### end Alembic commands ###
