"""add association_table_footer

Revision ID: 306d2ba37b33
Revises: 0bbb377ba822
Create Date: 2023-12-23 02:35:30.637472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306d2ba37b33'
down_revision: Union[str, None] = '0bbb377ba822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_footer',
    sa.Column('socials_id', sa.Integer(), nullable=True),
    sa.Column('block_footers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_footers_id'], ['block_footers.id'], ),
    sa.ForeignKeyConstraint(['socials_id'], ['socials.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_footer')
    # ### end Alembic commands ###
