"""is full

Revision ID: 37bd39d0813e
Revises: 47e3f8be9fb0
Create Date: 2023-12-20 13:00:40.012864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bd39d0813e'
down_revision: Union[str, None] = '47e3f8be9fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('is_fullscreen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'is_fullscreen')
    # ### end Alembic commands ###
