"""hero refactor

Revision ID: 3fe7f078b0c2
Revises: abec7f27c773
Create Date: 2023-12-19 21:26:40.466914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe7f078b0c2'
down_revision: Union[str, None] = 'abec7f27c773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('hero_button_id', sa.Integer(), nullable=True))
    op.add_column('banners', sa.Column('terms_button_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'banners', 'buttons', ['hero_button_id'], ['id'])
    op.create_foreign_key(None, 'banners', 'buttons', ['terms_button_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.drop_column('banners', 'terms_button_id')
    op.drop_column('banners', 'hero_button_id')
    # ### end Alembic commands ###
