"""rm ad block

Revision ID: 47e3f8be9fb0
Revises: dec4d16dc1f1
Create Date: 2023-12-20 12:50:20.355036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e3f8be9fb0'
down_revision: Union[str, None] = 'dec4d16dc1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('landings_block_add_id_fkey', 'landings', type_='foreignkey')
    op.drop_column('landings', 'block_add_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landings', sa.Column('block_add_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('landings_block_add_id_fkey', 'landings', 'add_blocks', ['block_add_id'], ['id'])
    # ### end Alembic commands ###
