"""#5 -> fix

Revision ID: 5455f2f28e50
Revises: 2cc074adca1c
Create Date: 2023-12-16 17:05:54.733682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5455f2f28e50'
down_revision: Union[str, None] = '2cc074adca1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_mains', sa.Column('buttons_id', sa.Integer(), nullable=False))
    op.drop_constraint('block_mains_participation_button_id_fkey', 'block_mains', type_='foreignkey')
    op.create_foreign_key(None, 'block_mains', 'buttons', ['buttons_id'], ['id'])
    op.drop_column('block_mains', 'participation_button_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_mains', sa.Column('participation_button_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'block_mains', type_='foreignkey')
    op.create_foreign_key('block_mains_participation_button_id_fkey', 'block_mains', 'buttons', ['participation_button_id'], ['id'])
    op.drop_column('block_mains', 'buttons_id')
    # ### end Alembic commands ###
