"""#3 -> fix

Revision ID: 55ad3fa84bb5
Revises: bcb5d5703253
Create Date: 2023-12-16 16:55:38.170647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ad3fa84bb5'
down_revision: Union[str, None] = 'bcb5d5703253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
