"""fix

Revision ID: 61148b04145f
Revises: f2da4fef5ef2
Create Date: 2023-12-19 22:12:57.702665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61148b04145f'
down_revision: Union[str, None] = 'f2da4fef5ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_bonuses', sa.Column('bg_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_bonuses', 'bg_color')
    # ### end Alembic commands ###
