"""#11 -> fix

Revision ID: 63e310abe682
Revises: cbd5c67253ce
Create Date: 2023-12-18 14:36:16.550879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e310abe682'
down_revision: Union[str, None] = 'cbd5c67253ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_blocks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('block_mains', sa.Column('title', sa.String(), nullable=False))
    op.add_column('success_popups', sa.Column('title', sa.String(), nullable=False))
    op.add_column('terms_popups', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms_popups', 'title')
    op.drop_column('success_popups', 'title')
    op.drop_column('block_mains', 'title')
    op.drop_column('add_blocks', 'title')
    # ### end Alembic commands ###
