"""add association_table_banner

Revision ID: 692499768ef8
Revises: f5b9a7dd45c8
Create Date: 2023-12-23 01:37:25.578225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692499768ef8'
down_revision: Union[str, None] = 'f5b9a7dd45c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_banner',
    sa.Column('banners_id', sa.Integer(), nullable=True),
    sa.Column('buttons_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banners_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['buttons_id'], ['buttons.id'], )
    )
    op.drop_constraint('banners_hero_button_id_fkey', 'banners', type_='foreignkey')
    op.drop_constraint('banners_terms_button_id_fkey', 'banners', type_='foreignkey')
    op.drop_column('banners', 'terms_button_id')
    op.drop_column('banners', 'hero_button_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('hero_button_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('banners', sa.Column('terms_button_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('banners_terms_button_id_fkey', 'banners', 'buttons', ['terms_button_id'], ['id'])
    op.create_foreign_key('banners_hero_button_id_fkey', 'banners', 'buttons', ['hero_button_id'], ['id'])
    op.drop_table('association_banner')
    # ### end Alembic commands ###
