"""add association_table_bonus

Revision ID: 85c11a4c4f87
Revises: 692499768ef8
Create Date: 2023-12-23 02:09:32.481038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c11a4c4f87'
down_revision: Union[str, None] = '692499768ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_bonus',
    sa.Column('bonuses_id', sa.Integer(), nullable=True),
    sa.Column('buttons_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bonuses_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['buttons_id'], ['buttons.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_bonus')
    # ### end Alembic commands ###
