"""#6 -> fix

Revision ID: 9536f435c8fe
Revises: 5455f2f28e50
Create Date: 2023-12-16 19:18:25.604456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9536f435c8fe'
down_revision: Union[str, None] = '5455f2f28e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonuses', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'button_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'value_bonus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonuses', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'value_bonus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'button_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
