"""#1

Revision ID: abb679044478
Revises: 5fa78595f877
Create Date: 2023-12-19 17:34:02.549700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abb679044478'
down_revision: Union[str, None] = '5fa78595f877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('json_landings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_slug', sa.String(), nullable=False),
    sa.Column('info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('landings', 'info_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landings', sa.Column('info_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('json_landings')
    # ### end Alembic commands ###
