"""btns to single

Revision ID: abec7f27c773
Revises: 6b0def865a46
Create Date: 2023-12-19 19:29:48.999773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abec7f27c773'
down_revision: Union[str, None] = '6b0def865a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_mains', 'buttons_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_mains', 'buttons_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
