"""init

Revision ID: b2f3d6f97781
Revises: 
Create Date: 2023-12-19 00:40:22.905469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f3d6f97781'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_banner', sa.String(), nullable=True),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('bg_img', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_block_bonus', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('analytics_endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactive_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_interactive_card', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_popups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('sub_text', sa.String(), nullable=True),
    sa.Column('sub_text_color', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_popups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_color', sa.String(), nullable=True),
    sa.Column('button_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_footers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_block_footer', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_bonus', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('button_id', sa.Integer(), nullable=True),
    sa.Column('value_bonus_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_bonuses.id'], ),
    sa.ForeignKeyConstraint(['value_bonus_id'], ['value_bonuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('sport_type_id', sa.Integer(), nullable=True),
    sa.Column('value_bonus_id', sa.Integer(), nullable=True),
    sa.Column('bk_id', sa.Integer(), nullable=True),
    sa.Column('button_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bk_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.ForeignKeyConstraint(['sport_type_id'], ['type_sports.id'], ),
    sa.ForeignKeyConstraint(['value_bonus_id'], ['value_bonuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_interactive', sa.String(), nullable=False),
    sa.Column('reset_button_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reset_button_id'], ['buttons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('selection_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('block_bonus_id', sa.Integer(), nullable=True),
    sa.Column('block_content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_bonus_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['block_content_id'], ['block_contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_mains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('interactive_id', sa.Integer(), nullable=True),
    sa.Column('buttons_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buttons_id'], ['buttons.id'], ),
    sa.ForeignKeyConstraint(['interactive_id'], ['interactive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_block_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.Column('block_bonus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_bonus_id'], ['block_bonuses.id'], ),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_block_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('block_contest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_contest_id'], ['block_contests.id'], ),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footer_id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['footer_id'], ['block_footers.id'], ),
    sa.ForeignKeyConstraint(['social_id'], ['socials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactive_interactive_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interactive_card_id', sa.Integer(), nullable=False),
    sa.Column('interactive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interactive_card_id'], ['interactive_cards.id'], ),
    sa.ForeignKeyConstraint(['interactive_id'], ['interactive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('info_json', sa.JSON(), nullable=True),
    sa.Column('block_terms_id', sa.Integer(), nullable=True),
    sa.Column('block_headers_id', sa.Integer(), nullable=True),
    sa.Column('block_banner_id', sa.Integer(), nullable=True),
    sa.Column('block_main_id', sa.Integer(), nullable=True),
    sa.Column('block_add_id', sa.Integer(), nullable=True),
    sa.Column('block_success_popup_id', sa.Integer(), nullable=True),
    sa.Column('block_bonus_id', sa.Integer(), nullable=True),
    sa.Column('block_footer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_add_id'], ['add_blocks.id'], ),
    sa.ForeignKeyConstraint(['block_banner_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['block_bonus_id'], ['block_bonuses.id'], ),
    sa.ForeignKeyConstraint(['block_footer_id'], ['block_footers.id'], ),
    sa.ForeignKeyConstraint(['block_headers_id'], ['block_headers.id'], ),
    sa.ForeignKeyConstraint(['block_main_id'], ['block_mains.id'], ),
    sa.ForeignKeyConstraint(['block_success_popup_id'], ['success_popups.id'], ),
    sa.ForeignKeyConstraint(['block_terms_id'], ['terms_popups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landings')
    op.drop_table('user_selections')
    op.drop_table('interactive_interactive_cards')
    op.drop_table('footer_socials')
    op.drop_table('contest_block_contests')
    op.drop_table('bonus_block_bonuses')
    op.drop_table('block_mains')
    op.drop_table('add_blocks')
    op.drop_table('users')
    op.drop_table('interactive')
    op.drop_table('contests')
    op.drop_table('bonuses')
    op.drop_table('block_headers')
    op.drop_table('block_footers')
    op.drop_table('block_contests')
    op.drop_table('banner_buttons')
    op.drop_table('value_bonuses')
    op.drop_table('type_sports')
    op.drop_table('type_bonuses')
    op.drop_table('terms_popups')
    op.drop_table('success_popups')
    op.drop_table('socials')
    op.drop_table('roles')
    op.drop_table('interactive_cards')
    op.drop_table('buttons')
    op.drop_table('bookmakers')
    op.drop_table('block_bonuses')
    op.drop_table('banners')
    # ### end Alembic commands ###
