"""#7 -> fix

Revision ID: c7d0b1fddb91
Revises: 9536f435c8fe
Create Date: 2023-12-16 19:30:40.053261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d0b1fddb91'
down_revision: Union[str, None] = '9536f435c8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonuses', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'button_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'value_bonus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bonuses', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonuses', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'value_bonus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'button_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
