"""#10 -> fix

Revision ID: cbd5c67253ce
Revises: 8fed20f3be8a
Create Date: 2023-12-18 14:33:55.473984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd5c67253ce'
down_revision: Union[str, None] = '8fed20f3be8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_headers', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_headers', 'title')
    # ### end Alembic commands ###
