"""add association_table_interactive

Revision ID: cc31b5353e53
Revises: 306d2ba37b33
Create Date: 2023-12-23 02:42:39.371653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc31b5353e53'
down_revision: Union[str, None] = '306d2ba37b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_interactive',
    sa.Column('interactive_id', sa.Integer(), nullable=True),
    sa.Column('interactive_cards_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interactive_cards_id'], ['interactive_cards.id'], ),
    sa.ForeignKeyConstraint(['interactive_id'], ['interactive.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_interactive')
    # ### end Alembic commands ###
