"""#8 -> fix

Revision ID: cf2a4ab363d3
Revises: c7d0b1fddb91
Create Date: 2023-12-17 17:16:21.679896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2a4ab363d3'
down_revision: Union[str, None] = 'c7d0b1fddb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_footers', sa.Column('title_block_footer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_footers', 'title_block_footer')
    # ### end Alembic commands ###
